name: CI & Release

on:
  # Build on pushes branches that have a PR (including drafts)
  pull_request:
  # Build on commits pushed to branches without a PR if it's in the allowlist
  push:
    branches: [main]
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:
    inputs:
      test:
        description: Run tests
        required: true
        default: true
        type: boolean
      release:
        description: Release new version
        required: true
        default: false
        type: boolean

concurrency:
  # On PRs builds will cancel if new pushes happen before the CI completes, as it defines `github.head_ref` and gives it the name of the branch the PR wants to merge into
  # Otherwise `github.run_id` ensures that you can quickly merge a queue of PRs without causing tests to auto cancel on any of the commits pushed to main.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint & Build
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.7.0
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: lts/*
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
        if: github.event.inputs.test != 'false'
      - run: pnpm run prepublishOnly

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.7.0
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  release:
    needs:
      - build
      - test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    # only run if opt-in during workflow_dispatch
    if: always() && github.event.inputs.release == 'true' && needs.build.result != 'failure' && needs.test.result != 'failure' && needs.test.result != 'cancelled'
    runs-on: ubuntu-latest
    name: Semantic release
    steps:
      - uses: actions/checkout@v3
        with:
          # Need to fetch entire commit history to
          # analyze every commit since last release
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.7.0
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: lts/*
      - run: pnpm install --frozen-lockfile
      - run: pnpm audit signatures
      - run: npx semantic-release
        # Don't allow interrupting the release step if the job is cancelled, as it can lead to an inconsistent state
        # e.g. git tags were pushed but it exited before `npm publish`
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
